### ISSUE TITLE
Error converting

### ISSUE THREAD

**Issue by denerFernandes** [fagbokforlaget/pdftohpubjs#5]
Hi, 
is not generating the full Hpub only generates the thumbs and ends, see:
```
node hpub.js
progress 4
progress 8
progress 13
progress 17
progress 21
progress 26
progress 30
progress 34
progress 39
progress 43
progress 47
undefined
```

Anyone know why this is?

Thank you.

**Comment by iapain** [comment]
Generating thumbnail required `pdftocairo`

**Comment by iapain** [comment]
Closing! Author not interested.
